name: 'Jekyll Deploy Action'

description: >
  A Github Action to deploy the Jekyll site conveniently for GitHub Pages

branding:
  icon: 'command'
  color: 'red'

inputs:
  id:
    description: The id according to os
    required: true
  owner:
    description: 'The deploy owner'
    required: false
  actor:
    description: 'The github username creating the commit'
    required: false
  token:
    description: 'The deploy token'
    required: false
  provider:
    description: 'The deploy provider'
    required: true
  credentials:
    description: 'The gcloud credentials'
    required: true
  pauli_sum:
    description: 'The pre-build configuration'
    required: true
  failure_status:
    description: 'The deploy branch'
    required: false

outputs:
  all_outputs:
    description: Collect all outputs
    value: ${{ toJSON(steps.*.outputs) }}

runs:
  #using: 'node20'
  #main: '.github/run/main.js'
  #post: '.github/run/post.js'
  #post-if: 'success()'
  using: composite
  
steps:
    - name: Target Configuration
      if: runner.os != 'Windows'
      uses: eq19/eq19/.github/actions/3-exponentiation/5-syntax@v1
      id: exponentiation
      with:
        hub_username: ${{ inputs.docker_hub_username }}
        hub_password: ${{ inputs.docker_hub_password }}
        failure_status: ${{ inputs.failure_status }}
        hub_token: ${{ inputs.docker_hub_token }}
        credentials: ${{ inputs.credentials }}
        action_path: ${{ github.action_path }}
        image_name: ${{ inputs.image_name }}
        token: ${{ inputs.token }}

    - name: Profiling Feedback
      if: runner.os == 'Windows'
      uses: eq19/eq19/.github/actions/4-identition/5-syntax@v1
      id: identition
      with:
        token: ${{ inputs.token }}
        image_name: ${{ inputs.image_name }}
        credentials: ${{ inputs.credentials }}
        workspace: ${GITHUB_WORKSPACE//\\//}
        action_path: ${GITHUB_ACTION_PATH//\\//}
        hub_token: ${{ inputs.docker_hub_token }} 
        failure_status: ${{ inputs.failure_status }}
        hub_username: ${{ inputs.docker_hub_username }}
