name: 'Jekyll Deploy Action'

description: >
  A Github Action to deploy the Jekyll site conveniently for GitHub Pages

branding:
  icon: 'command'
  color: 'red'

inputs:
  provider:
    description: 'The deploy provider'
    required: false
  owner:
    description: 'The deploy owner'
    required: false
  token:
    description: 'The deploy token'
    required: false
  credentials:
    description: 'The gcloud credentials'
    required: true
  repository:
    description: 'The deploy repository'
    required: false
  branch:
    description: 'The deploy branch'
    required: false
  actor:
    description: 'The github username creating the commit'
    required: false
  gell_mann:
    description: 'The pre-build configuration'
    required: true

runs:
  #using: 'node20'
  #main: '.github/run/main.js'
  #post: '.github/run/post.js'
  #post-if: 'success()'
  using: composite
  
  steps:
    - name: Build Jekyll pages
      if: runner.os != 'macOS'
      id: jekyll_site
      shell: bash
      run: |
        /home/runner/scripts/jekyll_site.sh

    - name: Collect output
      if: runner.os != 'macOS'
      uses: mathiasvr/command-output@v2.0.0
      id: command
      with:
        run: |
          date +'%Y-%m-%d'

    - name: Setup .NET SDK
      if: runner.os == 'macOS'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
