name: 'Jekyll Deploy Action'

description: >
  A Github Action to deploy the Jekyll site conveniently for GitHub Pages

branding:
  icon: 'command'
  color: 'red'

inputs:
  provider:
    description: 'The deploy provider'
    required: false
  owner:
    description: 'The deploy owner'
    required: false
  token:
    description: 'The deploy token'
    required: false
  credentials:
    description: 'The gcloud credentials'
    required: true
  repository:
    description: 'The deploy repository'
    required: false
  branch:
    description: 'The deploy branch'
    required: false
  actor:
    description: 'The github username creating the commit'
    required: false
  gell_mann:
    description: 'The pre-build configuration'
    required: true

runs:
  #using: 'node20'
  #main: '.github/run/main.js'
  #post: '.github/run/post.js'
  #post-if: 'success()'
  using: composite
  
  steps:
    # See https://cloud.google.com/functions
    - name: 🌀 Cloud Function Deployment 
      if: runner.os != 'Windows'
      uses: 'google-github-actions/deploy-cloud-functions@v3'
      id: 'deploy'
      with:
        name: 'my-function'
        runtime: 'nodejs20'
        project_id: feedmapping

    # See https://github.com/google-github-actions/deploy-cloud-functions
    - name: Example of using the output 
      if: runner.os != 'Windows'
      shell: bash
      run: 'curl "${{ steps.deploy.outputs.url }}"'

    - name: Collect output
      if: runner.os == 'Windows'
      uses: mathiasvr/command-output@v2.0.0
      id: command
      with:
        run: |
          date +'%Y-%m-%d'

