name: 'Jekyll Deploy Action'

description: >
  A Github Action to deploy the Jekyll site conveniently for GitHub Pages

branding:
  icon: 'command'
  color: 'red'

inputs:
  id:
    description: The id according to os
    required: true
  owner:
    description: 'The deploy owner'
    required: false
  actor:
    description: 'The github username creating the commit'
    required: false
  token:
    description: 'The deploy token'
    required: false
  provider:
    description: 'The deploy provider'
    required: true
  repository:
    description: 'The deploy repository'
    required: false
  credentials:
    description: 'The gcloud credentials'
    required: true
  pauli_sum:
    description: 'The pre-build configuration'
    required: true
  failure_status:
    description: 'The deploy branch'
    required: false

outputs:
  all_outputs:
    description: Collect all outputs
    value: ${{ toJSON(steps.*.outputs) }}

runs:
  #using: 'node20'
  #main: '.github/run/main.js'
  #post: '.github/run/post.js'
  #post-if: 'success()'
  using: composite
  
  steps:
    - name: 💎 Setup Ruby
      uses: ruby/setup-ruby@v1
      if: ${{ runner.os == 'Windows' && inputs.failure_status == 'false' }}
      with:
        cache-version: 1
        rubygems: default
        ruby-version: '3.3'
        bundler-cache: true
        working-directory: ${{ github.workspace }}
        
    - name: Build Jekyll pages
      if: ${{ runner.os == 'Windows' && inputs.failure_status == 'false' }}
      id: jekyll_site
      shell: bash
      run: |
        echo -e "\n$hr\nBuild Pages\n$hr" && cd "${RUNNER_TEMP}"
        git clone --single-branch -b 'gh-source' ${TARGET_REPOSITORY} gh-source && cd gh-source

        #Jekyll Quick Reference https://gist.github.com/DrOctogon/bfb6e392aa5654c63d12
        JEKYLL_GITHUB_TOKEN=${{ inputs.token }} DISABLE_WHITELIST=true bundle exec jekyll build --profile -t -p "${RUNNER_TEMP}/gh-source/_plugins" -d "${RUNNER_TEMP}/gh-source/docs"   

        if [[ "${TARGET_REPOSITORY}" == "eq19/eq19.github.io" ]]; then echo "www.eq19.com" > "${RUNNER_TEMP}/gh-source/docs/CNAME"; fi
        
        rm -rf "${{ github.workspace }}/*" && mv -f "${RUNNER_TEMP}/gh-source/*" "${{ github.workspace }}/"
        rm -rf "${{ github.workspace }}/docs/.nojekyll" && touch "${{ github.workspace }}/docs/.nojekyll"
