# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Build and deploy Jekyll site

# 💎 Runs on deployment targeting the default branch
on:
  # push:
    # branches: [eQ19]
  workflow_run:
    types: [completed] #requested
    workflows: ["pages-build-deployment"]

# 🪂 Allow only one concurrent deployment across the branches
concurrency:
  group: "pages"
  cancel-in-progress: true
  
# Sets permissions of the GITHUB_TOKEN
permissions: write-all

# Sets global environtment variables
env:
  OWNER: ${{ github.repository_owner }}

jobs:
  # Build job
  github-pages:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ${{ vars.OWNER != 'FeedMapping' && 'ubuntu-latest' || 'windows-latest' }}
    steps:
      - name: 📂 Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
 
      - name: 💎 Build on Linux
        if: runner.os == 'Linux'
        uses: eq19/feed@v2
        with:
          pre_build_commands: 'make build'
          token: ${{ secrets.JEKYLL_GITHUB_TOKEN }}

      - name: 💎 Build on Windows
        if: runner.os == 'Windows'
        uses: eq19/maps@v1
        id: stepid
        with:
          dotnet-version: '3.1.x'
