name: 'Docker Deploy Action'

description: >
  🪂  A Github Action to deploy pages conveniently

branding:
  icon: 'command'
  color: 'red'

inputs:
  hub_username:
    description: Username for Docker Hub
    default: ${{ github.actor }}       
    required: true
  hub_password:
    description: Docker Hub authentication token
    required: true
  hub_token:
    description: Docker Hub authentication token
    required: true
  image_name:
    description: "Name for the container to be created. Example: nginx"
    required: false
  action_path:
    description: Path to the dockerfile from which to build the image
    required: true

outputs:
  site_id:
    description: "A file path to a results file."
    value: ${{ env.ID}}

runs:
  using: composite
  steps:
    - name: 🚀 Initiate Lexer
      uses: devcontainers/ci@v0.3
      with:
        push: always
        runCmd: ls -alR /data
        skipContainerUserIdUpdate: true
        imageName: ${{ inputs.image_name }}
        imageTag: target-${{ github.run_number }}
        configFile: ${{ inputs.action_path }}/.devcontainer.json

    - name: 💎 Variables
      id: variables
      shell: bash
      run: |
        BASE_NAME=$(basename ${{ inputs.image_name }})
        IFS=', '; array=($(curl -L -s 'https://registry.hub.docker.com/v2/repositories/${{ inputs.image_name }}/tags?page_size=1024' | jq -rc '."results"[]["name"]' | yq eval -P | sed "s/ /, /g"))
        for ((i=0; i < ${#array[@]}; i++)); do
          if [ "${array[$i]}" != "latest" ]; then
            HUB_TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "{\"username\": \"${{ inputs.hub_username }}\", \"password\": \"${{ inputs.hub_password }}\"}" https://hub.docker.com/v2/users/login/ | jq -r .token)
            curl -s -i -X DELETE -H "Accept: application/json" -H "Authorization: JWT $HUB_TOKEN" https://hub.docker.com/v2/namespaces/${{ inputs.hub_username }}/repositories/$BASE_NAME/tags/${array[$i]}
            echo "deleted: ${{ inputs.image_name }}:${array[$i]}"
          fi
        done
